server:
  port: 8080

spring:
  security:
    saml2:
      relyingparty:
        registration:
          test-idp:
            assertingparty:
              metadata-uri: https://login.microsoftonline.com/common/federationmetadata/2007-06/federationmetadata.xml